---
# Author: jashi111
# Description: Playbook to install MongoDB 7.0 and configure the system
- name: Install and Configure MongoDB Replica Set
  hosts: mongodb
  become: true
  gather_facts: false
  vars_files:
    - vars.yml

  pre_tasks:

    - name: Stop MongoDB service
      ansible.builtin.systemd:
        name: mongod
        state: stopped
        enabled: false

    - name: Remove MongoDB packages
      ansible.builtin.apt:
        name: "mongodb-org*"
        state: absent
        purge: yes

    - name: Remove MongoDB data directory
      ansible.builtin.file:
        path: /var/lib/mongodb
        state: absent

    - name: Remove MongoDB log directory
      ansible.builtin.file:
        path: /var/log/mongodb
        state: absent

    - name: Remove MongoDB configuration file
      ansible.builtin.file:
        path: /etc/mongod.conf
        state: absent

    - name: Remove MongoDB repository file
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/mongodb-org-*.list"
        state: absent

    - name: Update APT package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Install pip using apt
      apt:
        name: python3-pip
        state: present


  tasks:
    - name: Install gnupg package
      apt:
        name: gnupg
        state: present
      register: gnupg_install
      #failed_when: gnupg_install.rc != 0

    - name: Download MongoDB GPG key
      become: true
      become_user: root
      shell: |
        curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc -o /etc/apt/trusted.gpg.d/mongodb-server-7.0.asc
      register: gpg_key
      #failed_when: "'error' in gpg_key.stderr or gpg_key.rc != 0"

    - name: Add MongoDB repository
      apt_repository:
        repo: "deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse"
        filename: mongodb-org-7.0
      register: repo_add
      #failed_when: repo_add.rc != 0

    - name: Install MongoDB Service v7.0.14
      apt:
        name:
          - mongodb-org=7.0.14
          - mongodb-org-database=7.0.14
          - mongodb-org-server=7.0.14
          - mongodb-mongosh
          - mongodb-org-mongos=7.0.14
          - mongodb-org-tools=7.0.14
        state: present
      register: mongodb_install
      #failed_when: mongodb_install.rc != 0

    - name: Reload systemd manager configuration
      systemd:
        daemon_reload: yes
      register: systemd_reload
      #failed_when: systemd_reload.rc != 0

    - name: Ensure MongoDB service is started
      service:
        name: mongod
        state: started
        enabled: true
      register: service_status
      #failed_when: service_status.rc != 0

    - name: Replace Values in mongod.conf
      replace:
        path: /etc/mongod.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - { regexp: '#  engine:', replace: '  engine: wiredTiger' }
        - { regexp: '127.0.0.1', replace: '0.0.0.0' }
        - { regexp: '#replication', replace: 'replication' }
      register: conf_replace
      #failed_when: conf_replace.failed > 0

    - name: Add Additional Data to mongod.conf
      lineinfile:
        path: /etc/mongod.conf
        insertafter: "{{ item.insert_after }}"
        line: "{{ item.new_line }}"
      loop:
        - { insert_after: "^systemLog:", new_line: "  logRotate: reopen" }
        - { insert_after: "^net:", new_line: "  bindIp: 0.0.0.0" }
        - { insert_after: "^replication:", new_line: "  oplogSizeMB: 1" }
        - { insert_after: "^replication:", new_line: "  replSetName: {{ REPLICA_NAME }}" }
      register: lineinfile_status
      #failed_when: lineinfile_status.failed > 0

    - name: Restart MongoDB
      service:
        name: mongod
        state: restarted
        enabled: true
      register: restart_status
      #failed_when: restart_status.rc != 0

    - name: Wait for little time
      pause:
          seconds: 10    
    
    - name: Ensure replicaset rs0 exists
      community.mongodb.mongodb_replicaset:
        login_host: "{{ groups['mongodb'][0] }}"
        login_user: admin
        login_password: admin
        replica_set: "{{ REPLICA_NAME }}"
        members:
          - host: "{{ groups['mongodb'][0] }}:27017"
          - host: "{{ groups['mongodb'][1] }}:27017"
          - host: "{{ groups['mongodb'][2] }}:27017"
        arbiter_at_index: 2
      when: inventory_hostname == groups['mongodb'][0]

    - name: Wait for little time
      pause:
          seconds: 10

    - name: Create 'facetone' database user with name 'duo' and password 'DuoS123'.
      community.mongodb.mongodb_user:
        database: "{{ DB_NAME }}"
        name: "{{ DB_USER }}"
        password: "{{ DB_PASSWRD }}"
        roles: readWrite,dbAdmin,userAdmin
        state: present
      when: inventory_hostname == groups['mongodb'][0]

